[package]
version = "1.0.0"
category = "Custom"
title = "FPS Measurement with Camera"
description = "FPS Measurement based on Custom Camera Trajectory"
authors = ["KKR"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "FPS_Measurement_with_Camera_python"
